<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\PowerLedger.Core\PowerLedger.Core.csproj" />
    <ProjectReference Include="..\..\src\PowerLedger.Contracts\PowerLedger.Contracts.csproj" />
    <ProjectReference Include="..\..\src\PowerLedger.Storage\PowerLedger.Storage.csproj" />
    <ProjectReference Include="..\..\src\PowerLedger.Sensors\PowerLedger.Sensors.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
