name = "powerledger-data"
main = "src/index.ts"
compatibility_date = "2026-08-22"

[[r2_buckets]]
binding = "REPORTS"
bucket_name = "powerledger-data"

[[d1_databases]]
binding = "DB"
database_name = "powerledger-index"
database_id = "9fb625e2-f540-4491-a9e6-f3ddc0f9348b"
migrations_dir = "migrations"

[[ratelimits]]
name = "ADDRESS_LIMIT"
namespace_id = "1001"
simple = { limit = 60, period = 60 }

[triggers]
crons = ["17 3 * * *"]
